name: Build and deploy ASP.Net Core app to Azure Web App - backend-eventservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore EventService/EventService.sln

      - name: Build solution
        run: dotnet build EventService/EventService.sln --configuration Release --no-restore

      - name: Publish API project
        run: dotnet publish EventService/EventService.WebApi/EventService.WebApi.csproj -c Release -o publish

      - name: Zip publish folder
        run: Compress-Archive -Path publish\* -DestinationPath publish.zip

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: publish.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_683F2F17F9924845B4A80EBBED585FC1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A5B3978591F749B99EA8A779CD14BF7A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45B337EA70C0417290F465ABFB663597 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-eventservice'
          slot-name: 'Production'
          package: publish.zip
